/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY, 
    name VARCHAR (20)  NOT NULL, 
    date_of_birth DATE NOT NULL, 
    escape_attempts INT NOT NULL, 
    neutered BOOLEAN SET DEFAULT false, 
    weight_kg DECIMAL NOT NULL, 
    PRIMARY KEY (id)
);

ALTER TABLE animals ADD species varchar(100);

CREATE TABLE owners (
    id INT GENERATED BY DEFAULT AS IDENTITY, 
    full_name VARCHAR(50) NOT NULL, 
    age INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE species (
    id INT GENERATED BY DEFAULT AS IDENTITY, 
    name VARCHAR(50) NOT NULL, 
    PRIMARY KEY (id)
);

ALTER TABLE animals DROP COLUMN species;
ALTER TABLE animals ADD species_id INT;
ALTER TABLE animals ADD CONSTRAINT FOREIGN KEY (species_id) REFERENCES species (id);
ALTER TABLE animals ADD owner_id INT;
ALTER TABLE animals ADD CONSTRAINT animals_owners FOREIGN KEY (owner_id) REFERENCES owners (id);

CREATE TABLE vets (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(20) NOT NULL,
    age INT,
    date_of_graduation DATE,
    PRIMARY KEY (id)
);